/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Comunicação.MinhaComunicacaoEnvio;
import Modelo.Conexao;
import Modelo.Usuario;

/**
 *
 * @author Bruno
 */
public class EncerrarLeilao extends javax.swing.JFrame {

    private static EncerrarLeilao instancia = new EncerrarLeilao();
    /**
     * Creates new form EncerrarLeilao
     */
    public EncerrarLeilao() {
        initComponents();
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Encerrar Meu Leilão Agora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 140, 195, 84);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario u = Usuario.getInstancia();
        if (u.getPapel().equalsIgnoreCase("servidor")) {
            Conexao c = Conexao.getInstancia();
            c.setStatusLeilao("finalizando");
        } else {
            MinhaComunicacaoEnvio envia = new MinhaComunicacaoEnvio();
            envia.setMensagem("15#" + u.getIdPublica() + "#" + u.getIdRede());
            envia.start();
        }
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static EncerrarLeilao getInstancia() {
        return instancia;
    }

    public static void setInstancia(EncerrarLeilao instancia) {
        EncerrarLeilao.instancia = instancia;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
