/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Janela de notificação ao cliente
 * @author Bruno Tokarski e Rafael Vidal
 */
public class JanelaNotificacao extends javax.swing.JDialog {

    /**
     * Creates new form Notificação
     */
    public JanelaNotificacao(String mensagem) {
        initComponents();
        jLabel1.setText(mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnIrLocacao = new javax.swing.JButton();
        btnFecharAviso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baixou!");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("notificacao");

        btnIrLocacao.setText("Ir para Locação!");
        btnIrLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrLocacaoActionPerformed(evt);
            }
        });

        btnFecharAviso.setText("Fechar Aviso");
        btnFecharAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIrLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(btnFecharAviso)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrLocacao)
                    .addComponent(btnFecharAviso))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Avançar para a tela de locação
     * @param evt 
     */
    private void btnIrLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrLocacaoActionPerformed
        try {
            dispose();
            JanelaLocacaoVeiculo jlv = new JanelaLocacaoVeiculo();
            jlv.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JanelaNotificacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIrLocacaoActionPerformed

    /**
     * Fechar a janela de notificação
     * @param evt 
     */
    private void btnFecharAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAvisoActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharAvisoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharAviso;
    private javax.swing.JButton btnIrLocacao;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
