/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import IOarquivo.IOCartao;
import Modelo.Cartao;
import java.util.ArrayList;

/**
 *
 * @author Rafael
 */
public class JanelaCartoes extends javax.swing.JDialog {

    /**
     * Creates new form JanelaCartoes
     */
    public JanelaCartoes() throws Exception {
        initComponents();
        setModal(true);
        CarregaCartoes();
    }
    
    /**
     * Carrega os cartões e popula a tabela
     */
    public void CarregaCartoes() throws Exception
    {
        IOCartao iocar = new IOCartao();
        
        ArrayList<Cartao> cartoes = iocar.RecuperarCartoes();
        
        Object[][] tabela = new Object[cartoes.size()][3];
        for (int i = 0; i < cartoes.size(); i++) {
            tabela[i][0] = cartoes.get(i).getIdCartao();
            tabela[i][1] = cartoes.get(i).getLocal();
            tabela[i][2] = cartoes.get(i).getProprietario().getNomeColecionador();
        }
        
        PopulaTabela(tabela);
    }
    
    public void PopulaTabela(Object[][] tabela) throws Exception
    {
        tbCartoes.setModel(new javax.swing.table.DefaultTableModel(
                tabela,
                new String[]{
                    "ID", "Local", "Proprietário"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
            };
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbCartoes.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tbCartoes);
        tbCartoes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbCartoes.getColumnModel().getColumnCount() > 0) {
            tbCartoes.getColumnModel().getColumn(0).setResizable(false);
            tbCartoes.getColumnModel().getColumn(0).setPreferredWidth(28);
            tbCartoes.getColumnModel().getColumn(1).setPreferredWidth(95);
            tbCartoes.getColumnModel().getColumn(2).setPreferredWidth(95);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbCartoes = new javax.swing.JTable();
        btnNovoCartao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tbCartoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cartão", "Descrição", "Proprietário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbCartoes);

        btnNovoCartao.setText("Novo Cartão");
        btnNovoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCartaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNovoCartao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCartaoActionPerformed
        JanelaCadastroCartao jcc = new JanelaCadastroCartao();
        jcc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNovoCartaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoCartao;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCartoes;
    // End of variables declaration//GEN-END:variables
}
