//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.0
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebService.WebServiceReferencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebService/", ConfigurationName="WebServiceReferencia.wsLocadora")]
    public interface wsLocadora {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento name no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/helloRequest", ReplyAction="http://WebService/wsLocadora/helloResponse")]
        ClienteWebService.WebServiceReferencia.helloResponse hello(ClienteWebService.WebServiceReferencia.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/helloRequest", ReplyAction="http://WebService/wsLocadora/helloResponse")]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.helloResponse> helloAsync(ClienteWebService.WebServiceReferencia.helloRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento return no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/ListarVeiculosRequest", ReplyAction="http://WebService/wsLocadora/ListarVeiculosResponse")]
        ClienteWebService.WebServiceReferencia.ListarVeiculosResponse ListarVeiculos(ClienteWebService.WebServiceReferencia.ListarVeiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/ListarVeiculosRequest", ReplyAction="http://WebService/wsLocadora/ListarVeiculosResponse")]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ListarVeiculosResponse> ListarVeiculosAsync(ClienteWebService.WebServiceReferencia.ListarVeiculosRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento return no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/ConsultarLocacoesVeiculoRequest", ReplyAction="http://WebService/wsLocadora/ConsultarLocacoesVeiculoResponse")]
        ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse ConsultarLocacoesVeiculo(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/ConsultarLocacoesVeiculoRequest", ReplyAction="http://WebService/wsLocadora/ConsultarLocacoesVeiculoResponse")]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse> ConsultarLocacoesVeiculoAsync(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento locacao no namespace  não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/EfetuarLocacaoRequest", ReplyAction="http://WebService/wsLocadora/EfetuarLocacaoResponse")]
        ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse EfetuarLocacao(ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebService/wsLocadora/EfetuarLocacaoRequest", ReplyAction="http://WebService/wsLocadora/EfetuarLocacaoResponse")]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse> EfetuarLocacaoAsync(ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(ClienteWebService.WebServiceReferencia.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ClienteWebService.WebServiceReferencia.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarVeiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarVeiculos", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.ListarVeiculosRequestBody Body;
        
        public ListarVeiculosRequest() {
        }
        
        public ListarVeiculosRequest(ClienteWebService.WebServiceReferencia.ListarVeiculosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarVeiculosRequestBody {
        
        public ListarVeiculosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarVeiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarVeiculosResponse", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.ListarVeiculosResponseBody Body;
        
        public ListarVeiculosResponse() {
        }
        
        public ListarVeiculosResponse(ClienteWebService.WebServiceReferencia.ListarVeiculosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarVeiculosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ListarVeiculosResponseBody() {
        }
        
        public ListarVeiculosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLocacoesVeiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLocacoesVeiculo", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequestBody Body;
        
        public ConsultarLocacoesVeiculoRequest() {
        }
        
        public ConsultarLocacoesVeiculoRequest(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarLocacoesVeiculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idVeiculo;
        
        public ConsultarLocacoesVeiculoRequestBody() {
        }
        
        public ConsultarLocacoesVeiculoRequestBody(int idVeiculo) {
            this.idVeiculo = idVeiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLocacoesVeiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLocacoesVeiculoResponse", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponseBody Body;
        
        public ConsultarLocacoesVeiculoResponse() {
        }
        
        public ConsultarLocacoesVeiculoResponse(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarLocacoesVeiculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ConsultarLocacoesVeiculoResponseBody() {
        }
        
        public ConsultarLocacoesVeiculoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EfetuarLocacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EfetuarLocacao", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequestBody Body;
        
        public EfetuarLocacaoRequest() {
        }
        
        public EfetuarLocacaoRequest(ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class EfetuarLocacaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string locacao;
        
        public EfetuarLocacaoRequestBody() {
        }
        
        public EfetuarLocacaoRequestBody(string locacao) {
            this.locacao = locacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EfetuarLocacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EfetuarLocacaoResponse", Namespace="http://WebService/", Order=0)]
        public ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponseBody Body;
        
        public EfetuarLocacaoResponse() {
        }
        
        public EfetuarLocacaoResponse(ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class EfetuarLocacaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public EfetuarLocacaoResponseBody() {
        }
        
        public EfetuarLocacaoResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsLocadoraChannel : ClienteWebService.WebServiceReferencia.wsLocadora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsLocadoraClient : System.ServiceModel.ClientBase<ClienteWebService.WebServiceReferencia.wsLocadora>, ClienteWebService.WebServiceReferencia.wsLocadora {
        
        public wsLocadoraClient() {
        }
        
        public wsLocadoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsLocadoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLocadoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsLocadoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.WebServiceReferencia.helloResponse ClienteWebService.WebServiceReferencia.wsLocadora.hello(ClienteWebService.WebServiceReferencia.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ClienteWebService.WebServiceReferencia.helloRequest inValue = new ClienteWebService.WebServiceReferencia.helloRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.helloRequestBody();
            inValue.Body.name = name;
            ClienteWebService.WebServiceReferencia.helloResponse retVal = ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.helloResponse> ClienteWebService.WebServiceReferencia.wsLocadora.helloAsync(ClienteWebService.WebServiceReferencia.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.helloResponse> helloAsync(string name) {
            ClienteWebService.WebServiceReferencia.helloRequest inValue = new ClienteWebService.WebServiceReferencia.helloRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.helloRequestBody();
            inValue.Body.name = name;
            return ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.WebServiceReferencia.ListarVeiculosResponse ClienteWebService.WebServiceReferencia.wsLocadora.ListarVeiculos(ClienteWebService.WebServiceReferencia.ListarVeiculosRequest request) {
            return base.Channel.ListarVeiculos(request);
        }
        
        public string ListarVeiculos() {
            ClienteWebService.WebServiceReferencia.ListarVeiculosRequest inValue = new ClienteWebService.WebServiceReferencia.ListarVeiculosRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.ListarVeiculosRequestBody();
            ClienteWebService.WebServiceReferencia.ListarVeiculosResponse retVal = ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).ListarVeiculos(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ListarVeiculosResponse> ClienteWebService.WebServiceReferencia.wsLocadora.ListarVeiculosAsync(ClienteWebService.WebServiceReferencia.ListarVeiculosRequest request) {
            return base.Channel.ListarVeiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ListarVeiculosResponse> ListarVeiculosAsync() {
            ClienteWebService.WebServiceReferencia.ListarVeiculosRequest inValue = new ClienteWebService.WebServiceReferencia.ListarVeiculosRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.ListarVeiculosRequestBody();
            return ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).ListarVeiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse ClienteWebService.WebServiceReferencia.wsLocadora.ConsultarLocacoesVeiculo(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest request) {
            return base.Channel.ConsultarLocacoesVeiculo(request);
        }
        
        public string ConsultarLocacoesVeiculo(int idVeiculo) {
            ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest inValue = new ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequestBody();
            inValue.Body.idVeiculo = idVeiculo;
            ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse retVal = ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).ConsultarLocacoesVeiculo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse> ClienteWebService.WebServiceReferencia.wsLocadora.ConsultarLocacoesVeiculoAsync(ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest request) {
            return base.Channel.ConsultarLocacoesVeiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoResponse> ConsultarLocacoesVeiculoAsync(int idVeiculo) {
            ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest inValue = new ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.ConsultarLocacoesVeiculoRequestBody();
            inValue.Body.idVeiculo = idVeiculo;
            return ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).ConsultarLocacoesVeiculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse ClienteWebService.WebServiceReferencia.wsLocadora.EfetuarLocacao(ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest request) {
            return base.Channel.EfetuarLocacao(request);
        }
        
        public bool EfetuarLocacao(string locacao) {
            ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest inValue = new ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequestBody();
            inValue.Body.locacao = locacao;
            ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse retVal = ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).EfetuarLocacao(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse> ClienteWebService.WebServiceReferencia.wsLocadora.EfetuarLocacaoAsync(ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest request) {
            return base.Channel.EfetuarLocacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebService.WebServiceReferencia.EfetuarLocacaoResponse> EfetuarLocacaoAsync(string locacao) {
            ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest inValue = new ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequest();
            inValue.Body = new ClienteWebService.WebServiceReferencia.EfetuarLocacaoRequestBody();
            inValue.Body.locacao = locacao;
            return ((ClienteWebService.WebServiceReferencia.wsLocadora)(this)).EfetuarLocacaoAsync(inValue);
        }
    }
}
